[package]
authors = ["Alan Ryan <alan.ryan@gmail.com>"]
edition = "2018"
name = "pi_drive_sync"
version = "0.1.0"
[dependencies]
google-drive3 = "*"
hyper = "^0.10"
hyper-rustls = "^0.6"
inotify = "*"
notify = "*"
serde = "^1.0"
serde_json = "^1.0"
tempfile = "3.1.0"
yup-oauth2 = "^1.0"
.
